[project]
name = "setup-oh-my-posh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathlib>=1.0.1",
    "readchar>=4.2.1",
    "typing>=3.10.0.0",
]
